version: '3'

services:
  arserver:
    image: arcor2/arcor2_arserver_kinali:${ARCOR2_VERSION:?ARCOR2_VERSION env variable not set}
    container_name: arserver
    depends_on:
      - project
      - build
      - execution
      - testitoff-robot-webapi
    ports:
      - "6789:6789"
    networks:
          - testitoff-robot-network
          - testitoff-search-network
    environment:
      - REST_ROBOT_SERVICE_URL=http://testitoff-robot-webapi:13000 
      - SEARCH_SERVICE_URL=http://testitoff-search-webapi:12000
      - ARCOR2_PERSISTENT_STORAGE_URL=http://project:11000            
      - ARCOR2_EXECUTION_URL=ws://execution:6790
      - ARCOR2_BUILDER_URL=http://build:5007
      - BARCODE_SERVICE_URL=""
  build:
    image: arcor2/arcor2_build:${ARCOR2_VERSION:?ARCOR2_VERSION env variable not set}
    container_name: build
    environment:
      - ARCOR2_PERSISTENT_STORAGE_URL=http://project:11000
    ports:
      - "5007:5007"
    networks:           
      - testitoff-robot-network
  execution:
    image: arcor2/arcor2_execution_kinali:${ARCOR2_VERSION:?ARCOR2_VERSION env variable not set}
    container_name: execution
    networks:
          - testitoff-robot-network
          - testitoff-search-network
    environment:
      - REST_ROBOT_SERVICE_URL=http://testitoff-robot-webapi:13000 
      - SEARCH_SERVICE_URL=http://testitoff-search-webapi:12000
      - ARCOR2_BUILDER_URL=http://build:5007
    ports:
      - "5009:5009"
  testitoff-robot-webapi:
      image: registry.gitlab.com/kinalisoft/test-it-off/robot-simulator:0.2.1
      container_name: "testitoff-robot-webapi"
      expose:
          - "13000"
      environment:
          - MONGODB_URL=testitoff-robot-mongodb:27017
      ports:
        - "13000:13000"
      links:
          - project
      restart: always
      networks:
        - testitoff-robot-network
  testitoff-robot-mongodb:
      image: mongo:4.2.0-bionic
      container_name: "testitoff-robot-mongodb"
      restart: always
      environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
      volumes:
          - testitoff-robot-mongodb:/data/db
      networks:
          - testitoff-robot-network
      expose:
          - "27017"
      ports:
          - "13017:27017"  

  
  testitoff-search-webapi:
        image: registry.gitlab.com/kinalisoft/test-it-off/search-simulator:latest
        container_name: "testitoff-search-webapi"
        privileged: true
        restart: always
        environment:
          - MONGODB_URL=testitoff-search-mongodb:27017
        ports:
          - "12000:12000"
        networks:
          - testitoff-search-network

  testitoff-search-mongodb:
        image: mongo:4.2.0-bionic
        container_name: "testitoff-search-mongodb"
        restart: always
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - testitoff-search-mongodb:/data/db
        networks:
            - testitoff-search-network
        expose:
            - "27017"
        ports:
            - "12017:27017" 

  project:
    image: registry.gitlab.com/kinalisoft/test-it-off/project-web-api:0.1.1
    container_name: "project"
    ports:
      - "11000-11001:11000-11001"
    environment:
      MONGODB_URL: mongodb:27017
    links:
        - mongodb
    depends_on:
        - mongodb
    networks:
      - testitoff-robot-network

  mongodb:
    image: mongo:4.2.0-bionic
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb:/data/db
    expose:
      - "27017"
    networks:
      - testitoff-robot-network

volumes:
  mongodb:   
  testitoff-robot-mongodb:  
  testitoff-search-mongodb:

networks:
  testitoff-robot-network: 
  testitoff-search-network:


