version: '3'

services:
  arserver:
    image: arcor2/arcor2_arserver_kinali:${ARCOR2_VERSION:?ARCOR2_VERSION env variable not set}
    container_name: arserver
    depends_on:
      - project
      - build
      - execution
      - testitoff-robot-webapi
    ports:
      - "6789:6789"
    networks:
          - testitoff-robot-network
          - testitoff-search-network
          - testitoff-barcode-network
          - testitoff-statistic-network 
          - testitoff-interaction-network
    environment:
      - REST_ROBOT_SERVICE_URL=http://testitoff-robot-webapi:13000 
      - SEARCH_SERVICE_URL=http://testitoff-search-webapi:12000
      - ARCOR2_PERSISTENT_STORAGE_URL=http://project:11000            
      - ARCOR2_EXECUTION_URL=ws://execution:6790
      - ARCOR2_BUILDER_URL=http://build:5007
      - BARCODE_SERVICE_URL=http://testitoff-barcode-webapi:14000
      - STATISTIC_SERVICE_URL=http://testitoff-statistic-webapi:16000
      - INTERACTION_SERVICE_URL=http://testitoff-interaction-webapi:17000

  build:
    image: arcor2/arcor2_build:${ARCOR2_BUILD_VERSION:?ARCOR2_BUILD_VERSION env variable not set}
    container_name: build
    environment:
      - ARCOR2_PERSISTENT_STORAGE_URL=http://project:11000
    ports:
      - "5007:5007"
    networks:           
      - testitoff-robot-network
      - testitoff-barcode-network
      - testitoff-search-network
      - testitoff-statistic-network 
      - testitoff-interaction-network
  execution:
    image: arcor2/arcor2_execution_kinali:${ARCOR2_EXECUTION_VERSION:?ARCOR2_EXECUTION_VERSION env variable not set}
    container_name: execution
    networks:
          - testitoff-robot-network
          - testitoff-search-network
          - testitoff-barcode-network 
          - testitoff-statistic-network 
          - testitoff-interaction-network
    environment:
      - REST_ROBOT_SERVICE_URL=http://testitoff-robot-webapi:13000 
      - SEARCH_SERVICE_URL=http://testitoff-search-webapi:12000
      - BARCODE_SERVICE_URL=http://testitoff-barcode-webapi:14000
      - STATISTIC_SERVICE_URL=http://testitoff-statistic-webapi:16000
      - ARCOR2_BUILDER_URL=http://build:5007
    ports:
      - "5009:5009"
  testitoff-robot-webapi:
      image: registry.gitlab.com/kinalisoft/test-it-off/robot-simulator:0.4.1
      container_name: "testitoff-robot-webapi"
      expose:
          - "13000"
      environment:
          - MONGODB_URL=testitoff-robot-mongodb:27017
      ports:
        - "13000:13000"
      links:
          - project
      restart: always
      networks:
        - testitoff-robot-network
  testitoff-robot-mongodb:
      image: mongo:4.2.0-bionic
      container_name: "testitoff-robot-mongodb"
      restart: always
      environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
      volumes:
          - testitoff-robot-mongodb:/data/db
      networks:
          - testitoff-robot-network
      expose:
          - "27017"
      ports:
          - "13017:27017"  

  
  testitoff-search-webapi:
        image: registry.gitlab.com/kinalisoft/test-it-off/search-simulator:0.4.0
        container_name: "testitoff-search-webapi"
        privileged: true
        restart: always
        environment:
          - MONGODB_URL=testitoff-search-mongodb:27017
        ports:
          - "12000:12000"
        networks:
          - testitoff-search-network

  testitoff-search-mongodb:
        image: mongo:4.2.0-bionic
        container_name: "testitoff-search-mongodb"
        restart: always
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - testitoff-search-mongodb:/data/db
        networks:
            - testitoff-search-network
        expose:
            - "27017"
        ports:
            - "12017:27017" 

  testitoff-barcode-webapi:
        image: registry.gitlab.com/kinalisoft/test-it-off/barcode-simulator:0.1.2
        container_name: "testitoff-barcode-webapi"
        privileged: true
        restart: always
        environment:
          - MONGODB_URL=testitoff-barcode-mongodb:27017
        ports:
          - "14000:14000"
        networks:
          - testitoff-barcode-network

  testitoff-barcode-mongodb:
        image: mongo:4.2.0-bionic
        container_name: "testitoff-barcode-mongodb"
        restart: always
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - testitoff-barcode-mongodb:/data/db
        networks:
            - testitoff-barcode-network
        expose:
            - "27017"
        ports:
            - "14017:27017"

  testitoff-interaction-webapi:
        image: registry.gitlab.com/kinalisoft/test-it-off/interaction:0.1.0
        container_name: "testitoff-interaction-webapi"
        privileged: true
        restart: always
        environment:
          - MONGODB_URL=testitoff-interaction-mongodb:27017
        ports:
          - "17000:17000"
        networks:
          - testitoff-interaction-network

  testitoff-interaction-mongodb:
        image: mongo:4.2.0-bionic
        container_name: "testitoff-interaction-mongodb"
        restart: always
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - testitoff-interaction-mongodb:/data/db
        networks:
            - testitoff-interaction-network
        expose:
            - "27017"
        ports:
            - "17017:27017"


  testitoff-statistic-webapi:
        image: registry.gitlab.com/kinalisoft/test-it-off/statistic:0.1.0
        container_name: "testitoff-statistic-webapi"
        privileged: true
        restart: always
        environment:
          - MONGODB_URL=testitoff-statistic-mongodb:27017
        ports:
          - "16000:16000"
        networks:
          - testitoff-statistic-network

  testitoff-statistic-mongodb:
        image: mongo:4.2.0-bionic
        container_name: "testitoff-statistic-mongodb"
        restart: always
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - testitoff-statistic-mongodb:/data/db
        networks:
            - testitoff-statistic-network
        expose:
            - "27017"
        ports:
            - "16017:27017"



  project:
    image: registry.gitlab.com/kinalisoft/test-it-off/project-web-api:0.2.0
    container_name: "project"
    ports:
      - "11000-11001:11000-11001"
    environment:
      MONGODB_URL: mongodb:27017
    links:
        - mongodb
    depends_on:
        - mongodb
    networks:
      - testitoff-robot-network

  mongodb:
    image: mongo:4.2.0-bionic
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb:/data/db
    expose:
      - "27017"
    networks:
      - testitoff-robot-network

volumes:
  mongodb:   
  testitoff-robot-mongodb:  
  testitoff-search-mongodb:
  testitoff-barcode-mongodb:
  testitoff-statistic-mongodb:
  testitoff-interaction-mongodb:

networks:
  testitoff-robot-network: 
  testitoff-search-network:
  testitoff-barcode-network:
  testitoff-statistic-network:
  testitoff-interaction-network:

