version: '3'

services:
  arcor:
    build: ./arcor2_kinali
    container_name: arcor2
    command: ["/wait-for", "http://database:5001/projects", "--","/bin/bash", "/start.sh"]
    depends_on:
      - database
    ports:
      - "6789:6789"
    environment:
      - ARCOR2_KINALI_RESTAPI_ADDRESS=http://kinali:5000 
      - ARCOR2_PERSISTENT_STORAGE_URL=http://database:5001
#    volumes:
#      - C:\arcor2\arcor2:/root/arcor2/arcor2
#      - C:\arcor2\arcor2\object_types:/root/arcor2/arcor2/object_types
#      - C:\arcor2_kinali\arcor2_kinali:/root/arcor2_kinali/arcor2_kinali
  kinali:
    image: office.kinalisoft.eu:8082/kinalisoft-pickmaster-restserver:0.1.0-alpha.4
    container_name: kinali
    ports:
      - "5000:5000"
  database:
    build: ./database
    command: /bin/bash /start.sh
    environment:
      - ARCOR2_MONGO_ADDRESS=localhost:27017
    ports:
      - "5001:5001"            
#    volumes:
#      - C:\arcor2\arcor2:/root/arcor2/arcor2