version: '3'

services:
  arcor:
    build: ./arcor2_kinali
    container_name: arcor2
    command: /bin/bash /root/arcor2_kinali/docker/arcor2_kinali/start.sh
    depends_on:
      - database
    ports:
      - "6789:6789"
    environment:
      - ARCOR2_MONGO_ADDRESS=database:27017
      - ARCOR2_KINALI_RESTAPI_ADDRESS=http://kinali:5000 
    volumes:
      - C:\arcor2\arcor2:/root/arcor2/arcor2
      - C:\arcor2\arcor2\object_types:/root/arcor2/arcor2/object_types
      - C:\arcor2_kinali\arcor2_kinali:/root/arcor2_kinali/arcor2_kinali
  kinali:
    image: office.kinalisoft.eu:8082/kinalisoft-pickmaster-restserver:0.1.0-alpha.3
    container_name: kinali
    ports:
      - "5000:5000"
  database:
    image: mongo:latest