version: '3'

services:
  arcor:
    image: arcor2/arcor2:0.2.2
    container_name: arcor2
    command: ["/wait-for", "http://pickmaster-storage:11000/projects", "--","/bin/bash", "/start.sh"]
    depends_on:
      - pickmaster-storage
    ports:
      - "6789:6789"
    environment:
      - ARCOR2_KINALI_RESTAPI_ADDRESS=http://kinali:10000 
      - ARCOR2_PERSISTENT_STORAGE_URL=http://pickmaster-storage:11000
#    volumes:
#      - C:\arcor2\arcor2:/root/arcor2/arcor2
#      - C:\arcor2\arcor2\object_types:/root/arcor2/arcor2/object_types
#      - C:\arcor2_kinali\arcor2_kinali:/root/arcor2_kinali/arcor2_kinali
#      - C:\arcor2_kinali\swagger_client:/root/arcor2_kinali/swagger_client
  pickmaster-restserver:
        image: office.kinalisoft.eu:8082/kinalisoft-pickmaster-restserver-mock:0.1.0-alpha.8
        container_name: "pickmaster-restserver"
        ports:
          - "10000-10001:10000-10001"
        environment:
          STORAGE_URL: pickmaster-storage:11000
        links:
            - pickmaster-storage
        depends_on:
            - pickmaster-storage

  pickmaster-storage:
    image: kinalisoft/storage:0.3.1
    container_name: "pickmaster-storage"
    ports:
      - "11000-11001:11000-11001"
    environment:
      MONGODB_URL: pickmaster-mongodb:27017
    links:
        - pickmaster-mongodb
    depends_on:
        - pickmaster-mongodb

  pickmaster-mongodb:
    image: mongo:4.2.0-bionic
    container_name: "pickmaster-mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb:/data/db
    expose:
      - "27017"

volumes:
  mongodb:   

